### ISSUE TITLE
Batch resolve

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-dedupe#136] opened 2020-11-17 15:51 UTC
same as old app.
user should be able to:
- mark all dedupes on the current page as either MAX or SUM
- hit a button which will push all 50 resolutions to the db

**Comment by jakub-bao** [comment] 2020-11-17 18:21
UI directions:

Instead of having the Edit Selected Items menu at the top of the screen, it should be in the place of the filters pane.

Between Data Deduplication and Dedupe Type, have two tabs, one called Filter Dedupes which is what is displayed there now. The other should be called Batch Edit and should have the following buttons:

Use maximum
Use sum
Resolve
Unresolve
Select all
Select none
(Note the icons from the wireframe.)

The user should be able to switch between tabs at will. When any checkboxes are selected, then the tab should switch to Batch Edit.

**Comment by jakub-bao** [comment] 2020-12-08 16:17
Select:
* Select all
* Select none

Use resolution method: 
* Use maximum
* Use sum

Resolve:
* Resolve all
* Unresolve all

**Comment by benguaraldi** [comment] 2020-12-08 16:27
Method: 
* Use maximum
* Use sum

Action:
* Select all visible
* Select all that match search
* Unselect all
* Resolve
* Unresolve

**Comment by benguaraldi** [comment] 2020-12-17 17:24
We're going to make batch unresolving not MVP, so I'll make a new ticket for that.

**Comment by benguaraldi** [comment] 2020-12-17 17:25
@DavidNesbitt2020, could you test this to make sure it works properly?  Note that @jakub-bao and I had discussions, and the final implementation is a little bit different than the description above, so don't worry about that (unless you see a UI or functionality problem).

**Comment by DavidNesbitt2020** [comment] 2020-12-17 18:44
Possible bug: If the selection is made > then method > but undone by the user, it still leaves all fields "selected" to be resolved. I think we might be missing an "UNSELECT ALL" in the method box so that a user can undo their method selection too.

Steps to reproduce:

1) Search pure dedupes after filtering
![image](https://user-images.githubusercontent.com/73136568/102528561-bad37d00-406c-11eb-9353-28b9e93f7958.png)

2) Navigate to "Batch" button at top, and select "SELECT EVERYTHING"
![image](https://user-images.githubusercontent.com/73136568/102528802-05ed9000-406d-11eb-9cf5-cfb6f5ef9a17.png)

3) Select method "SET TO MAXIMUM":
![image](https://user-images.githubusercontent.com/73136568/102528942-42b98700-406d-11eb-93c4-5259c9e5e3d7.png)

4) Then as the user I think, "wait, I meant to do something else" and click "UNSELECT ALL", it still leaves everything set to be resolved from the previous method selection.
![image](https://user-images.githubusercontent.com/73136568/102529245-a04dd380-406d-11eb-9f40-fa1a6b97cd87.png)

**Comment by DavidNesbitt2020** [comment] 2020-12-17 18:46
Other functionality works when I resolve dedupes using batch:

![image](https://user-images.githubusercontent.com/73136568/102529646-3255dc00-406e-11eb-9342-b92783ed786d.png)

**Comment by benguaraldi** [comment] 2020-12-17 18:55
@ssearle-bao, please see @DavidNesbitt2020's [comment above](https://github.com/pepfar-datim/datim-dedupe/issues/136#issuecomment-747625970).  I think this is the correct behavior, but let me know if you think something different should happen.

Probably this is fine for MVP either way, but let me know if either of you disagree.

**Comment by DavidNesbitt2020** [comment] 2020-12-17 19:22
@benguaraldi and @jakub-bao 
I rescind my comment here: https://github.com/pepfar-datim/datim-dedupe/issues/136#issuecomment-747626773

While testing #146 , I realized that every dedupe was designated as "unresolved", but I was testing it after having resolved 20 dedupes in the batch app there.  Although my screen shot in my comment above shows green "resolved dedupes", once I clicked away, they are not resolved!

![image](https://user-images.githubusercontent.com/73136568/102533312-3fc19500-4073-11eb-9d59-6162c7e374d1.png)

**Comment by benguaraldi** [comment] 2020-12-23 15:21
@DavidNesbitt2020 and talked and we've got some more non-MVP issues to add based on https://github.com/pepfar-datim/datim-dedupe/issues/136#issuecomment-747626773, but we'll talk about those in other tickets.

The main thing is that Batch resolve isn't actually resolving the dedupes.  @jakub-bao, could you look into that?

**Comment by benguaraldi** [comment] 2021-01-05 18:17
@ssearle-bao I was hoping that you'd comment on this:
https://github.com/pepfar-datim/datim-dedupe/issues/136#issuecomment-747632372

**Comment by ssearle-bao** [comment] 2021-01-06 15:41
OK, thanks for the flag @benguaraldi  - sorry I missed this. 

I chatted with @DavidNesbitt2020 a bit on this. I think we definitely need the unselect as a feature at some point, and David points out that it would be a big help from a usability/data quality perspective, but it's OK with me if it's not MVP. Let's target it for whatever the next version is, however.

@DavidNesbitt2020 , does that seem ok?

**Comment by DavidNesbitt2020** [comment] 2021-01-06 15:54
Mostly!  :)

My first issue flagged above is asking that we include an "Unselect Method" option for the user. Especially since we already have an "Unselect All" Selection in the box above it. For consistency's sake, I'm recommending we add an "Unselect Method". I think it _should be expected behavior_ to unselect method too and thus, an MVP (which Ben and I broke off into ticket #156). 

@ssearle-bao - I think Ben and I are asking for you to weigh in as the "tie-breaker" for https://github.com/pepfar-datim/datim-dedupe/issues/136#issuecomment-747625970 and #156 which address the same thing.

Having an general UNDO feature (#157) is probably a lot of work at this point, and can be targeted for a subsequent release. So not MVP.

**Comment by benguaraldi** [comment] 2021-01-06 15:58
Thanks, @DavidNesbitt2020!  Yes, let's close this.  @ssearle-bao, if you could decide whether #156 is MVP over in #156, that would be helpful.

**Comment by ssearle-bao** [comment] 2021-01-06 15:59
Cool, thanks both....heading over to #156 :)

**Closed** 2021-01-06 15:59 UTC
Labels: MVP, testing
