### ISSUE TITLE
Error checking on Resolve/Unresolve

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-dedupe#163] opened 2020-12-23 16:32 UTC
The Resolve/Unresolve process doesn't correctly capture if the request failed. 
I'd try to Resolve on `ben.datim.org`. The server is responding with `409` but the UI acts like the operation was successful.

![image](https://user-images.githubusercontent.com/47790868/103018067-92d39600-4512-11eb-9b14-be5ea4ae5c60.png)

**Comment by benguaraldi** [comment] 2021-01-13 18:30
3**: Say `Session expired`
4**: Show the error message
No response: Say `Cannot reach server`
Otherwise: Say `Unknown error`

**Comment by benguaraldi** [comment] 2021-01-13 18:31
Also:
- Errors should not disappear, except when dismissed
- Errors should be a little more visible, maybe bigger

**Comment by benguaraldi** [comment] 2021-02-01 17:30
3** errors and No response will be taken care of by #176 and #188.

So this ticket is just the 4** errors.

**Comment by benguaraldi** [comment] 2021-02-02 22:08
I locked the data set, but the Dedupe app is still able to modify the values!

@hardingt, is that expected behavior?

**Comment by hardingt** [comment] 2021-02-03 13:37
@benguaraldi 
A) depends how many other datasets there are they may still be open for that data element/period
B) you are a superuser right? Superusers can do things to datasets to bypass some locks. I would try it as as an IA user

**Comment by benguaraldi** [comment] 2021-02-03 19:50
@hardingt I tried it as an IA user and I am still able to enter dedupe data after the data set is locked.

Note that I cannot enter data in the Dedupe mech in the Data Entry app—only in the Dedupe app.

**Comment by hardingt** [comment] 2021-02-03 20:33
@benguaraldi are we 100% sure the value is being saved then? That's interesting. My guess is it might be something with A. Can you steal the network command and change the year to the future or past and see if that has any effect?

**Comment by benguaraldi** [comment] 2021-02-03 21:28
@hardingt Yes, I can see the change happening in the Data Entry app.

So...this is interesting...because the Dedupe app is not sending the `ds` parameter, DHIS2 appears to not be checking whether the data set is locked, even for Interagency users.  I also tried setting all data sets to 1 expiry day and going back several years in the past, and they both had no effect.

Check out the following code:
[changeDataWithoutDataset.py.zip](https://github.com/pepfar-datim/datim-dedupe/files/5921464/changeDataWithoutDataset.py.zip)

This is the same behavior as the old app, so I don't think we need to change this for MVP.

However, we do need to consider three things:
1. Is this a bug in DHIS2 to not check the data set if it is not specified?
2. Sometime later, should we change the Dedupe app to check the data set?
3. How on earth do we test this ticket?

**Comment by benguaraldi** [comment] 2021-02-03 21:30
Never mind! I think I figured it out! More in a moment.

**Comment by benguaraldi** [comment] 2021-02-03 21:32
Yay!  It worked!

![Screen Shot 2021-02-03 at 4 31 34 PM](https://user-images.githubusercontent.com/852673/106812203-5466e600-663d-11eb-88f7-4d8c3a9fd5e1.png)

Closing.

**Closed by benguaraldi** 2021-02-03 21:32 UTC
Labels: MVP, Ready to be tested
