### ISSUE TITLE
Crosswalk dedupes: Totals from different mechanisms is displayed instead of comparing between DSD and TA

### ISSUE THREAD

**Issue by srihtanguturi** [pepfar-datim/datim-dedupe#185] opened 2021-01-22 19:57 UTC
@benguaraldi
Env: nr.testing.datim.org
User: interagencytester1
App: Data deduplication 2.0.0
Mech IDs; 17007, 17275

The user is seeing totals of all the values entered for different mechanisms on the Crosswalk Dedupes page instead of comparing the values between DSD and TA.

In the below screenshots, the values are shown differently between versions for the same data fields 

**DataDeduplication 2.0.0 Screenshot:**
![image](https://user-images.githubusercontent.com/24919495/105536528-7e73ec00-5cbe-11eb-8d2e-7f0250c1afcc.png)

**Data Deduplication 1.5.6 Screenshot:**
![image](https://user-images.githubusercontent.com/24919495/105536688-bbd87980-5cbe-11eb-9733-0408c1054c5f.png)

Steps to reproduce:
1. Login as a partner1 user and navigate to Data Entry page
2. Choose below options and enter value in field
**OU** - Bobirwa District
**DataSet** - MER Results: Community Based
**Period** - Oct-Dec 2020
**Funding Mechanism**: 17007
Enter a value in PWID, Positive DSD field
![image](https://user-images.githubusercontent.com/24919495/105537894-9fd5d780-5cc0-11eb-8902-aaca214a6485.png)

3. Login as a partner2 user and navigate to Data Entry page
4. Choose below options and enter value in field
**OU** - Bobirwa District
**DataSet** - MER Results: Community Based
**Period** - Oct-Dec 2020
**Funding Mechanism**: 17275
5. Select the DSD tab and enter a value in PWID, Positive
![image](https://user-images.githubusercontent.com/24919495/105538175-03f89b80-5cc1-11eb-9c44-41fa5b5e2d08.png)
6. Select the TA-SDI tab and enter a value in PWID, Positive
![image](https://user-images.githubusercontent.com/24919495/105538314-36a29400-5cc1-11eb-84e4-11960b588e0c.png)
7. Login as Interagency user and navigate to Data Deduplication 2.0.0 page
8. Search for Crosswalk dedupe and verify that dupes are displayed for the values entered between DSD and TA-SDI tabs.

Refer to the screenshots above

**Comment by oodujebe** [comment] 2021-01-22 20:10
cc: @benguaraldi

**Comment by benguaraldi** [comment] 2021-01-22 21:53
Interesting.  I couldn't find user `interagencytester1`, @srihtanguturi—did it get deleted?

However, even from a superuser, it appears the new Dedupe is requesting a slightly different query than the old Dedupe did.

[Here is the old query](https://nr.testing.datim.org/api/sqlViews/wzpSd6j89wc/data?paging=false&var=ou:l1KFEXKI4Dg&var=dt:RESULTS&var=pe:2020Q4&var=ty:CROSSWALK&var=rs:true&var=ps:100000&var=pg:1&var=ag:NONE&var=dg:NONE&cache=8689691280898957) and [here is the new query](https://nr.testing.datim.org/api/sqlViews/wzpSd6j89wc/data?cacheBuster=1611352069490&paging=false&var=ou:l1KFEXKI4Dg&var=pe:2020Q4&var=rs:false&var=ps:50&var=pg:1&var=dt:RESULTS&var=ty:CROSSWALK&var=ag:FPUgmtt8HRi&var=dg:NONE).

The differences are:

parameter | old | new | notes
-|-|-|-
rs | true | false | not sure what this is
ps | 100000 | 50 | page size—this shouldn't matter
ag | NONE | FPUgmtt8HRi | not sure what this is either

@hardingt, @jakub-bao, @jason-p-pickering, any insight?

**Comment by benguaraldi** [comment] 2021-01-22 21:56
Upon further reflection, it seems that the user interface leads to the difference between the queries.

**Comment by benguaraldi** [comment] 2021-01-22 22:19
I see what the problem is here.  And it's an interesting one.  I'm not sure how we should resolve.

So with Dedupe 1.5.6, you had to finish doing pure dedupes before you got to crosswalk dedupes.  And the crosswalk dedupes would take the pure dedupes into consideration.  So if mech A had 20 and mech B had 10 and the dedupe was `Max`, then the total of mech A + mech B would be 20.  If the dedupe was `Sum`, then it would be 30.

However, if the dedupe is unresolved, the DSD total would *also* be 30.

Let's say the TA total is 40.  Some confusion could set in if the user, say, set the crosswalk dedupe first to `Sum` (i.e., 70) and then went back and set the pure dedupe to `Max` (i.e., 20).  Then the crosswalk dedupe total wouldn't match what the user originally picked.  Or even more confusingly, if the crosswalk dedupe is first set to `Sum` (i.e., 40) then the database has a -30 in the dedupe mech, which is trouble if the user sets a pure dedupe of `Max` (i.e., 20).

I'm also getting some weird behavior if I set crosswalk dedupe and then pure dedupe—sometimes the crosswalk dedupe disappears, even though I'm pretty sure it isn't being deleted when I set the pure dedupe.

@jakub-bao, could you look into the crosswalk dedupe disappearing bug?

@ssearle-bao, @hardingt, @DavidNesbitt2020, @jason-p-pickering, any sense of what to do about the crosswalk before pure dedupe issue?

**Comment by benguaraldi** [comment] 2021-01-23 03:39
@jakub-bao, I spun off the crosswalk dedupe disappearing into a separate bug: #187

**Comment by hardingt** [comment] 2021-01-25 15:22
@benguaraldi and @jason-p-pickering and @jakub-bao 
I think that for the MVP, we should make sure that the users have _finished_ their pure dedupes before allowing crosswalks

IF they've done a crosswalk dupe, and a new value shows up, it invalidates both the associated pure, and the associated crosswalk dupe. I believe that is already integrated into the query (it throws those out).

I think we should include this logic here, but am willing to be overruled!

The only time it gets extra weird is if a partner user is reporting data WHILE the the IA user is deduping. The program (PEPFAR) is set up in such a way to minimize this, but this is something to think about in the future. A warning if not all the deduping mechs are submitted by partner.

**Comment by jason-p-pickering** [comment] 2021-01-25 15:35
Pure dedupes must be resolved prior to crosswalks. 

Lets consider this situation

Mech 1 DSD- 20
Mech 2 DSD-30
Mech 3 TA - 50

User resolves the pure DSD as "MAX", thus, they get -20 going to the 00000 mech, with the DSD data element. 

They are presented with "30" as the "DSD value" in the next phase. The reason for this is because "DSD trumps TA". They then proceed to put a custom value of "20" (which is the lowest possible value), which means the 00001 mech gets -30 and it ALWAYS goes to the TA data element in a crosswalk. They MUST know the final pure dedupe value in order to know what the possible crosswalk will be, thus the enforcement of this workflow.

**Comment by benguaraldi** [comment] 2021-01-25 21:58
Thanks, @hardingt and @jason-p-pickering!  It seems like the most straightforward thing to do is to block the crosswalk dedupes on a dedupe-by-dedupe basis.  I've modified the SQL to flag any crosswalk dedupe that's based on an unresolved pure dedupe.  @jakub-bao's javascript can take it from there.

@jakub-bao, please have the UI read something like:
"Please resolve the pure dedupe before the crosswalk dedupe"

Thanks!

**Comment by benguaraldi** [comment] 2021-01-28 21:21
Go @jakub-bao!  This is now working properly on nr.testing.datim.org except for some formatting issues:
![Screen Shot 2021-01-28 at 4 20 26 PM](https://user-images.githubusercontent.com/852673/106200366-db6f1680-6184-11eb-887c-948f01607e4c.png)

**Comment by benguaraldi** [comment] 2021-01-28 21:28
@jakub-bao Actually, now that I look at it, it's probably wrong that it's showing a resolution and status for the crosswalk dedupe.  If the pure dedupe is unresolved.  Let me know if you want a separate ticket for that.

For the record, this is a more normal view:
![Screen Shot 2021-01-28 at 4 28 13 PM](https://user-images.githubusercontent.com/852673/106201037-dced0e80-6185-11eb-8fdf-3cb85608f2c7.png)

**Comment by benguaraldi** [comment] 2021-01-29 21:07
Looks good to me.  Thanks, @jakub-bao!  Closing.

**Closed by benguaraldi** 2021-01-29 21:07 UTC
Labels: MVP
