### ISSUE TITLE
Allow for filtering of dedupes by organisation unit branch

### ISSUE THREAD

**Issue by jason-p-pickering** [pepfar-datim/datim-dedupe#112] opened 2020-01-24 07:30 UTC
Add a new paramater to the backend to filter all dedupes within a single branch of the organisation unit hierarchy. 

Implement a tree picker in the UI to allow for users to choose a single organisation unit, and thus filter all dedupes within that branch.

**Comment by jakub-bao** [comment] 2020-01-24 15:44
Hi @jason-p-pickering No problem on this one. Can you go ahead with implementing the backend first and then let me know I'll add the UI?

**Comment by benguaraldi** [comment] 2020-12-14 21:24
Duplicate of #119.

**Closed by benguaraldi** 2020-12-14 21:24 UTC
